# Generated by Django 4.2.1 on 2023-05-31 15:21

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=pathlib.PurePosixPath('/home/anton/PycharmProjects/Map_Parser/media')),
        ),
    ]
